version: '3'
services:

  registry-service:
    image: registry-service-1.0:latest
#    restart: always
    ports:
      - 8001:8001
    environment:
#      SPRING_APPLICATION_NAME: eureka

  papients-service:
    image: papients-service-1.0:latest
    restart: always
    hostname: localhost
    expose:
      - 8002
    ports:
      - 8002:8002
    depends_on:
      - eureka

    environment:
      SPRING_APPLICATION_NAME: message-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:7777/eureka/


  gateway-service:
    image: gateway-service-1.0:latest

    #    restart: always
    expose:
      - 8889
    ports:
      - 8080:8080

    environment:
      SPRING_APPLICATION_NAME: gateway-service
      #EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_PROFILES_ACTIVE: enableEureka
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:7777/eureka/
#      ZUUL_ROUTES_HELLO_SERVICE_URL: http://localhost:9081
#      ZUUL_ROUTES_MESSAGE_SERVICE_URL: http://localhost:9080
#      ZUUL_ROUTES_REGISTRY_URL: http://localhost:7777
#      ZUUL_PREFIX: /services
