version: '3'
services:
  registry-service:
    image: registry-service-1.0:latest
    hostname: localhost
#    restart: always
    expose:
      - 8001
    ports:
      - 8001:8001
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8761/eureka/
      #      SPRING_APPLICATION_NAME: message-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
  db:
#      restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fhir
      - MONGO_INITDB_ROOT_PASSWORD=fhir
      - MONGODB_USERNAME=fhir
      - MONGODB_PASSWORD=fhir
      - MONGODB_DATABASE=fhir
    expose:
      - 27017
    ports:
      - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null

  patients-service:
    image: patients-service-1.0:latest
    restart: always
    hostname: localhost

    expose:
      - 8002
    ports:
      - 8002:8002
    depends_on:
      - registry-service
      - db
    environment:
      SPRING_DATA_MONGODB_DATABASE: admin
      #      SPRING_APPLICATION_NAME: message-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8001/eureka/

  diagnosis-service:
    image: diagnosis-service-1.0:latest
    restart: always
    hostname: localhost

    expose:
      - 8003
    ports:
      - 8003:8003
    depends_on:
      - registry-service
#      - mongod

    environment:
      SPRING_APPLICATION_NAME: diagnosis-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8001/eureka/

  gateway-service:
    image: gateway-service-1.0:latest
#    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"
#
#    environment:
#      SPRING_APPLICATION_NAME: gateway-service
      #EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
#      SPRING_PROFILES_ACTIVE: enableEureka
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:7777/eureka/
#      ZUUL_ROUTES_HELLO_SERVICE_URL: http://localhost:9081
#      ZUUL_ROUTES_MESSAGE_SERVICE_URL: http://localhost:9080
#      ZUUL_ROUTES_REGISTRY_URL: http://localhost:7777
#      ZUUL_PREFIX: /services

  observation-service:
    image: observation-service-1.0:latest
    restart: always
    hostname: localhost
    expose:
      - 8004
    ports:
      - 8004:8004
    depends_on:
      - registry-service
#      - mongod
    environment:
      SPRING_APPLICATION_NAME: observation-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8001/eureka/

  superhero-detection-service:
    image: superhero-detection-service-1.0:latest
    restart: always
    hostname: localhost
    expose:
      - 8005
    ports:
      - 8005:8005
    depends_on:
      - registry-service
      - db
    environment:
      SPRING_APPLICATION_NAME: superhero-detection-service
      #      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      #      SPRING_PROFILES_ACTIVE: enableEureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-service:8001/eureka/
